export const validationQuestions = {
  category_questions: [
    {
      id: "industry",
      question: "What industry or sector does your idea belong to?",
      options: [
        "Technology / Software",
        "Healthcare / Wellness",
        "E-commerce / Retail",
        "Education / EdTech",
        "Finance / FinTech",
        "Food & Beverage",
        "Real Estate",
        "Entertainment / Media",
        "Transportation / Logistics",
        "Other",
      ],
    },
    {
      id: "target_audience",
      question: "Who is your primary target audience?",
      options: [
        "Individual consumers (B2C)",
        "Small businesses (B2B SMB)",
        "Enterprise companies (B2B Enterprise)",
        "Non-profits / Organizations",
        "Students / Educational institutions",
        "Other",
      ],
    },
    {
      id: "business_model",
      question: "What is your primary business model?",
      options: [
        "SaaS (Subscription)",
        "Marketplace / Platform",
        "E-commerce / Product sales",
        "Freemium",
        "Consulting / Services",
        "Advertising / Media",
        "Other",
      ],
    },
  ],
  idea_explanation_questions: [
    {
      id: "problem",
      question: "What problem does your idea solve?",
      options: [
        "Saves time or increases efficiency",
        "Reduces costs or expenses",
        "Improves convenience or accessibility",
        "Solves a communication or connection gap",
        "Addresses a health or wellness need",
        "Fixes a quality or reliability issue",
        "Other problem",
      ],
    },
    {
      id: "solution",
      question: "How does your solution work?",
      options: [
        "Software / App / Platform",
        "Physical product / Hardware",
        "Service / Consulting",
        "Marketplace connecting buyers and sellers",
        "Content / Information / Education",
        "Community / Network / Social platform",
        "Other solution type",
      ],
    },
    {
      id: "uniqueness",
      question: "What makes your idea unique or different?",
      options: [
        "Better technology or features",
        "Lower price or better value",
        "Better user experience or design",
        "Serves an underserved market",
        "Faster or more convenient",
        "Better quality or reliability",
        "Not sure yet / Still exploring",
      ],
    },
    {
      id: "users",
      question: "Who would use your product or service?",
      options: [
        "General consumers / Everyone",
        "Small business owners",
        "Professionals / Freelancers",
        "Students / Young adults",
        "Parents / Families",
        "Seniors / Retirees",
        "Specific niche group",
      ],
    },
    {
      id: "revenue",
      question: "How do you plan to make money?",
      options: [
        "Monthly / Annual subscription",
        "One-time purchase",
        "Transaction fees / Commission",
        "Advertising revenue",
        "Freemium (free + paid features)",
        "Consulting / Services",
        "Not sure yet",
      ],
    },
  ],
};

