import { useMemo } from "react";
import { Link, useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import Seo from "../components/Seo.jsx";

const posts = [
  {
    slug: "ai-startup-ideas-for-product-managers",
    title: "7 AI Startup Ideas for Busy Product Managers",
    description: "Use your product chops to launch AI-powered solutions without leaving your day job.",
    date: "2025-11-07",
    tags: ["AI", "Product", "Side business"],
    body: `### Why this matters
Product leaders already translate customer needs into shipped features. With AI, you can package that skill into:

1. **Workflow copilots** for niche verticals (e.g. legal intake, clinical research).
2. **Insight automation** turning docs and meetings into prioritized backlogs.
3. **Validation as a service**: use your discovery toolkit to offer fast research sprints for founders.

### Quick validation tasks
- Run 5 customer interviews using our validation script.
- Build a landing page with your distinct POV and collect waitlist sign ups.
- Prototype a GPT-based workflow in Retool or Bubble.

### When to move to MVP
Once you see 10+ waitlist sign-ups or a consulting client ready to pay, channel that into a lightweight MVP and run the crew again for risk planning.`,
  },
  {
    slug: "validate-a-startup-idea-in-60-minutes",
    title: "Validate a Startup Idea in 60 Minutes",
    description: "A repeatable playbook to go from raw idea to signal without quitting your job.",
    date: "2025-11-04",
    tags: ["Validation", "Playbook"],
    body: `### 60 minute sprint
1. **Minute 0-10:** Run Startup Idea Advisor with your profile.
2. **Minute 10-30:** Pick the top idea and outline assumptions.
3. **Minute 30-45:** Draft a landing page or LinkedIn post testing value prop.
4. **Minute 45-60:** DM 5 people that match the persona and ask for interviews.

### Metrics to track
- Click-through rate on the landing page
- Interview acceptance rate
- Signals of willingness to pay

Keep the loop tight. Rerun the crew after each learning cycle for updated risks and roadmap.`,
  },
];

function usePost(slug) {
  return useMemo(() => posts.find((post) => post.slug === slug), [slug]);
}

function ShareLinks({ title, slug }) {
  const url = `https://startupideaadvisor.com/blog/${slug}`;
  const text = encodeURIComponent(`${title} - Startup Idea Advisor`);
  return (
    <div className="flex flex-wrap gap-2 text-sm text-slate-500">
      <span>Share:</span>
      <a
        href={`https://www.linkedin.com/shareArticle?mini=true&url=${encodeURIComponent(url)}&title=${text}`}
        target="_blank"
        rel="noreferrer"
        className="rounded-full bg-brand-50 px-3 py-1 text-brand-700 hover:bg-brand-100"
      >
        LinkedIn
      </a>
      <a
        href={`https://twitter.com/intent/tweet?url=${encodeURIComponent(url)}&text=${text}`}
        target="_blank"
        rel="noreferrer"
        className="rounded-full bg-brand-50 px-3 py-1 text-brand-700 hover:bg-brand-100"
      >
        X
      </a>
    </div>
  );
}

export default function BlogPage() {
  const { slug } = useParams();
  const post = usePost(slug);

  if (post) {
    return (
      <article className="grid gap-4 rounded-3xl border border-slate-200 bg-white/90 p-8 shadow-soft">
        <Seo
          title={`${post.title} | Startup Idea Advisor`}
          description={post.description}
          path={`/blog/${post.slug}`}
          keywords={`startup ideas, ${post.tags.join(", ")}`}
        />
        <p className="text-xs uppercase tracking-wide text-slate-400">{new Date(post.date).toLocaleDateString()}</p>
        <h1 className="text-3xl font-semibold text-slate-900">{post.title}</h1>
        <ShareLinks title={post.title} slug={post.slug} />
        <div className="prose prose-slate">
          <ReactMarkdown>{post.body}</ReactMarkdown>
        </div>
        <div className="flex justify-between text-sm text-brand-600">
          <Link to="/blog">← Back to blog</Link>
          <Link to="/" className="underline">Run a new idea</Link>
        </div>
      </article>
    );
  }

  return (
    <section className="grid gap-6 rounded-3xl border border-slate-200 bg-white/90 p-8 shadow-soft">
      <Seo
        title="AI Startup Idea Blog | Startup Idea Advisor"
        description="Insights, playbooks, and weekly ideas generated by our AI advisor to inspire your next venture."
        path="/blog"
      />
      <h1 className="text-3xl font-semibold text-slate-900">Ideas & Playbooks</h1>
      <p className="text-slate-600">
        Weekly insights and curated ideas from the Startup Idea Advisor crew. Subscribe to stay ahead of the curve.
      </p>
      <div className="grid gap-4">
        {posts.map((post) => (
          <article key={post.slug} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-xs uppercase tracking-wide text-slate-400">
              {new Date(post.date).toLocaleDateString()}
            </p>
            <h2 className="mt-1 text-xl font-semibold text-slate-900">{post.title}</h2>
            <p className="mt-2 text-sm text-slate-600">{post.description}</p>
            <div className="mt-3 flex flex-wrap gap-2 text-xs uppercase tracking-wide text-brand-600">
              {post.tags.map((tag) => (
                <span key={tag} className="rounded-full bg-brand-50 px-3 py-1">{tag}</span>
              ))}
            </div>
            <div className="mt-4 flex items-center gap-3 text-sm text-brand-600">
              <Link to={`/blog/${post.slug}`} className="font-medium underline">
                Read article
              </Link>
              <ShareLinks title={post.title} slug={post.slug} />
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
