import { useEffect } from "react";
import { useLocation } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import { useReports } from "../context/ReportsContext.jsx";
import Seo from "../components/Seo.jsx";

function useQuery() {
  return new URLSearchParams(useLocation().search);
}

export default function ProfileReport() {
  const { reports, loadRunById } = useReports();
  const query = useQuery();
  const runId = query.get("id");

  useEffect(() => {
    if (runId) {
      loadRunById(runId);
    }
  }, [runId, loadRunById]);

  return (
    <section className="rounded-3xl border border-slate-200 bg-white/95 p-8 shadow-soft">
      <Seo
        title="Profile Analysis Report | Startup Idea Advisor"
        description="Detailed analysis of your entrepreneurial profile generated by our AI crew."
        path="/results/profile"
      />
      <h1 className="text-2xl font-semibold text-slate-900 mb-4">Profile Summary</h1>
      <div className="prose prose-slate">
        <ReactMarkdown>{reports?.profile_analysis || "No report available."}</ReactMarkdown>
      </div>
    </section>
  );
}
